"use client";

import { useState, useCallback, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useSummaryStore, LOADING_MESSAGES } from "@/store/summaryStore";
import { useAuthStore } from "@/store/authStore";
import { api } from "@/lib/api";
import { wordCount, estimateReadingTime, formatSeconds, getReadabilityLabel, getSentimentColor, truncateText } from "@/lib/utils";
import {
  FileText, Link2, Upload, Sparkles, Copy, Download, RefreshCw,
  ChevronDown, List, AlignLeft, Clock, BarChart3, Hash, TrendingUp,
  CheckCircle2, AlertCircle, Loader2, X, Star, Files,
} from "lucide-react";

const lengthOptions = [
  { value: "short" as const, label: "Short", desc: "~60 words" },
  { value: "medium" as const, label: "Medium", desc: "~128 words" },
  { value: "detailed" as const, label: "Detailed", desc: "~256 words" },
];

const languageOptions = [
  { value: "english", label: "English" },
  { value: "hindi", label: "Hindi" },
  { value: "french", label: "French" },
  { value: "spanish", label: "Spanish" },
  { value: "arabic", label: "Arabic" },
] as const;

export default function SummarizePage() {
  const store = useSummaryStore();
  const { token } = useAuthStore();
  const [copied, setCopied] = useState(false);
  const [loadingIdx, setLoadingIdx] = useState(0);
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (!store.isLoading) return;

    const nextMessage = LOADING_MESSAGES[Math.min(loadingIdx, LOADING_MESSAGES.length - 1)];

    if (store.loadingMessage !== nextMessage) {
      store.setLoading(true, nextMessage);
    }
  }, [loadingIdx, store]);

  const extractMultiDocuments = useCallback(() => {
    return store.inputText
      .split(/\n\s*---\s*\n/)
      .map((doc) => doc.trim())
      .filter(Boolean);
  }, [store.inputText]);

  const handleSummarize = useCallback(async () => {
    store.setLoading(true, LOADING_MESSAGES[0]);
    setLoadingIdx(0);

    const interval = setInterval(() => {
      setLoadingIdx((i) => Math.min(i + 1, LOADING_MESSAGES.length - 1));
    }, 2000);

    try {
      let result;
      if (store.inputMode === "multi") {
        const documents = extractMultiDocuments();
        result = await api.summarizeMulti({ documents, length: store.summaryLength, bullet_mode: store.bulletMode, target_language: store.targetLanguage, external_fact_check: store.externalFactCheckEnabled }, token);
      } else if (store.inputMode === "url") {
        result = await api.summarizeURL({ url: store.inputURL, length: store.summaryLength, bullet_mode: store.bulletMode, target_language: store.targetLanguage, external_fact_check: store.externalFactCheckEnabled }, token);
      } else if (store.inputMode === "file" && store.inputFile) {
        result = await api.summarizeFile(store.inputFile, store.summaryLength, store.bulletMode, store.targetLanguage, token);
      } else {
        result = await api.summarizeText({ text: store.inputText, length: store.summaryLength, bullet_mode: store.bulletMode, target_language: store.targetLanguage, external_fact_check: store.externalFactCheckEnabled }, token);
      }
      store.setResult(result);
    } catch (e: any) {
      store.setError(e.message || "Summarization failed");
    } finally {
      clearInterval(interval);
    }
  }, [store, token, extractMultiDocuments]);

  const handleCopy = () => {
    if (store.result) {
      navigator.clipboard.writeText(store.result.summary);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownload = () => {
    if (!store.result) return;
    const content = `# ${store.result.headline || "Summary"}\n\n${store.result.summary}\n\n## Key Points\n${store.result.key_points.map((p) => `- ${p}`).join("\n")}\n\n---\nGenerated by Briefly`;
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "summary.md";
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) store.setInputFile(file);
  };

  const canSubmit = store.inputMode === "text"
    ? store.inputText.length >= 50
    : store.inputMode === "multi"
      ? extractMultiDocuments().length >= 2 && extractMultiDocuments().every((doc) => doc.length >= 50)
      : store.inputMode === "url"
        ? store.inputURL.length >= 10
        : !!store.inputFile;
  const inputWords = store.inputMode === "text" ? wordCount(store.inputText) : 0;

  const s = {
  section: {
    width: "98%",
    maxWidth: "2500px",
    margin: "0 auto",
    padding: "55px  80px",
        minHeight: "calc(100vh - 64px)",
    backgroundImage:
      " url('https://unilamp.co.th/userfiles/unilamp/images/Projects/Bharat%20Mandapam%2C%20Venue%20of%20G20%20summit%2C%20Pragati%20Maidan/Bharat%20Mandapam%2C%20Venue%20of%20G20%20summit%2013.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundAttachment: "fixed",
  } as React.CSSProperties
};
  return (
    <div style={s.section}>
      {/* Header */}
      <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} style={{ marginBottom: "32px" }}>
        <h1
  style={{
    fontFamily: "var(--font-sans)",
    fontSize: "clamp(2rem, 4vw, 3rem)",
    fontWeight: 500,
    letterSpacing: "-0.04em",
    margin: 0,
    color: "var(--text-primary)",
  }}
>
  Summarize
</h1>
        <p
  style={{
    color: "var(--text-primary)",
    marginTop: "10px",
    fontSize: "1rem",
    lineHeight: 1.7,
  }}
>
          Summarize a single article, multiple articles, a URL, or an uploaded document.
        </p>
      </motion.div>

      <div
  style={{
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "28px",
    alignItems: "start",
  }}
  className="summarize-grid"
>
        {/* ── LEFT: INPUT PANEL ── */}
        <motion.div initial={{ opacity: 0, x: -16 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.1 }} style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
          {/* Mode Tabs */}
          <div style={{ display: "flex", gap: "4px", padding: "4px", borderRadius: "var(--radius-md)", backgroundColor: "var(--bg-secondary)", border: "1px solid var(--border-subtle)" }}>
            {([['text', 'Text', FileText], ['multi', 'Multi-Doc', Files], ['url', 'URL', Link2], ['file', 'File', Upload]] as const).map(([mode, label, Icon]) => (
              <button key={mode} onClick={() => store.setInputMode(mode)} style={{
                flex: 1, display: "flex", alignItems: "center", justifyContent: "center", gap: "6px", padding: "10px", borderRadius: "var(--radius-sm)", border: "none", fontSize: "0.8125rem", fontWeight: 500, cursor: "pointer",
                backgroundColor: store.inputMode === mode ? "var(--bg-card)" : "transparent",
                color: store.inputMode === mode ? "var(--text-primary)" : "var(--text-muted)",
                boxShadow: store.inputMode === mode ? "var(--shadow-sm)" : "none", transition: "all 0.2s ease",
              }}>
                <Icon size={14} /> {label}
              </button>
            ))}
          </div>

          {/* Input Area */}
          <div
  style={{
    borderRadius: "20px",
    border: "1px solid #dce5e9",
    backgroundColor: "#ffffff",
    overflow: "hidden",
    boxShadow: "0 8px 30px rgba(11,52,69,0.06)",
  }}
>
            {(store.inputMode === "text" || store.inputMode === "multi") && (
              <div style={{ position: "relative" }}>
               <textarea
                  value={store.inputText}
                  onChange={(e) => store.setInputText(e.target.value)}
                  placeholder={
                    store.inputMode === "multi"
                      ? "Paste multiple article texts and separate them with ---"
                      : "Paste your article text here... (minimum 50 characters)"
                  }
                  style={{
                    width: "100%",
                    minHeight: "390px",
                    padding: "24px",
                    border: "none",
                    outline: "none",
                    resize: "vertical",
                    fontFamily: "var(--font-sans)",
                    fontSize: "1rem",
                    lineHeight: 1.7,
                    backgroundColor: "transparent",
                    color: "var(--text-primary)",
                  }}
                />
                <div style={{ padding: "8px 20px 12px", display: "flex", justifyContent: "space-between", borderTop: "1px solid var(--border-subtle)", fontSize: "0.75rem", color: "var(--text-muted)" }}>
                  <span>{store.inputMode === "multi" ? `${extractMultiDocuments().length} documents` : `${inputWords} words`}</span>
                  <span>{store.inputMode === "multi" ? "Combined summary" : `~${estimateReadingTime(inputWords)} min read`}</span>
                </div>
              </div>
            )}
            {store.inputMode === "url" && (
              <div style={{ padding: "20px" }}>
                <div style={{ display: "flex", alignItems: "center", gap: "10px", padding: "14px 16px", borderRadius: "var(--radius-md)", border: "1px solid var(--border-default)", backgroundColor: "var(--bg-input)" }}>
                  <Link2 size={16} style={{ color: "var(--text-muted)", flexShrink: 0 }} />
                  <input type="url" value={store.inputURL} onChange={(e) => store.setInputURL(e.target.value)} placeholder="https://example.com/article" style={{
                    flex: 1, border: "none", outline: "none", fontSize: "0.9375rem", backgroundColor: "transparent", color: "var(--text-primary)", fontFamily: "var(--font-sans)",
                  }} />
                </div>
                <p style={{ marginTop: "12px", fontSize: "0.8125rem", color: "var(--text-muted)" }}>
                  Works with most news sites, blogs, and article pages.
                </p>
              </div>
            )}
            {store.inputMode === "file" && (
              <div style={{ padding: "20px" }}>
                <div onClick={() => fileInputRef.current?.click()} style={{
                  border: "2px dashed var(--border-default)", borderRadius: "var(--radius-md)", padding: "48px 24px", textAlign: "center", cursor: "pointer", transition: "all 0.2s ease",
                }}>
                  <Upload size={32} style={{ color: "var(--text-muted)", marginBottom: "12px" }} />
                  {store.inputFile ? (
                    <div>
                      <p style={{ fontWeight: 500, color: "var(--text-primary)" }}>{store.inputFile.name}</p>
                      <p style={{ fontSize: "0.8125rem", color: "var(--text-muted)", marginTop: "4px" }}>{(store.inputFile.size / 1024).toFixed(1)} KB</p>
                    </div>
                  ) : (
                    <div>
                      <p style={{ fontWeight: 500, color: "var(--text-secondary)" }}>Click to upload a file</p>
                      <p style={{ fontSize: "0.8125rem", color: "var(--text-muted)", marginTop: "4px" }}>PDF, DOCX, or TXT (max 10MB)</p>
                    </div>
                  )}
                </div>
                <input ref={fileInputRef} type="file" accept=".pdf,.docx,.txt" onChange={handleFileChange} style={{ display: "none" }} />
              </div>
            )}
          </div>

          {/* Controls */}
          <div style={{ display: "flex", gap: "12px", flexWrap: "wrap", alignItems: "center" }}>
            {/* Length Selector */}
            <div style={{ display: "flex", gap: "4px", padding: "4px", borderRadius: "var(--radius-md)", backgroundColor: "var(--bg-secondary)", border: "1px solid var(--border-subtle)" }}>
              {lengthOptions.map((opt) => (
                <button key={opt.value} onClick={() => store.setSummaryLength(opt.value)} style={{
                  padding: "8px 14px", borderRadius: "var(--radius-sm)", border: "none", fontSize: "0.8125rem", fontWeight: 500, cursor: "pointer",
                  backgroundColor: store.summaryLength === opt.value ? "var(--bg-card)" : "transparent",
                  color: store.summaryLength === opt.value ? "var(--text-primary)" : "var(--text-muted)",
                  boxShadow: store.summaryLength === opt.value ? "var(--shadow-sm)" : "none", transition: "all 0.2s ease",
                }}>
                  {opt.label}
                </button>
              ))}
            </div>

            {/* Bullet Mode */}
            <button onClick={() => store.setBulletMode(!store.bulletMode)} style={{
              display: "flex", alignItems: "center", gap: "6px", padding: "8px 14px", borderRadius: "var(--radius-md)", border: "1px solid var(--border-default)", fontSize: "0.8125rem", fontWeight: 500, cursor: "pointer",
              backgroundColor: store.bulletMode ? "var(--accent-primary-light)" : "var(--bg-card)",
              color: store.bulletMode ? "var(--accent-primary)" : "var(--text-tertiary)", transition: "all 0.2s ease",
            }}>
              <List size={14} /> Bullets
            </button>

            {/* Language Selector */}
            <label style={{ display: "flex", alignItems: "center", gap: "8px", padding: "8px 12px", borderRadius: "var(--radius-md)", border: "1px solid var(--border-default)", backgroundColor: "var(--bg-card)" }}>
              <span style={{ fontSize: "0.8125rem", color: "var(--text-muted)" }}>Language</span>
              <select
                value={store.targetLanguage}
                onChange={(e) => store.setTargetLanguage(e.target.value as any)}
                style={{ border: "none", background: "transparent", color: "var(--text-primary)", fontSize: "0.8125rem", fontWeight: 500, outline: "none", cursor: "pointer" }}
              >
                {languageOptions.map((option) => (
                  <option key={option.value} value={option.value}>{option.label}</option>
                ))}
              </select>
            </label>

          <button
            onClick={() =>
              store.setExternalFactCheckEnabled(!store.externalFactCheckEnabled)
            }
            style={{
              display: "flex",
              alignItems: "center",
              gap: "6px",
              padding: "8px 14px",
              borderRadius: "var(--radius-md)",
              border: "1px solid var(--border-default)",
              fontSize: "0.8125rem",
              fontWeight: 700,
              cursor: "pointer",

              backgroundColor: store.externalFactCheckEnabled
                ? "var(--bg-secondary)"
                : "var(--bg-card)",

              color: store.externalFactCheckEnabled
                ? "var(--text-primary)"
                : "var(--text-tertiary)",

              transition: "all 0.2s ease",
            }}
          >
            <CheckCircle2 size={14} />
            {store.externalFactCheckEnabled
              ? "External check on"
              : "External check off"}
          </button>
          </div>

          {/* Submit Button */}
          <button onClick={handleSummarize} disabled={!canSubmit || store.isLoading} style={{
            display: "flex", alignItems: "center", justifyContent: "center", gap: "8px", padding: "14px 24px", borderRadius: "var(--radius-md)", border: "none",
            backgroundColor: canSubmit && !store.isLoading ? "var(--accent-primary)" : "var(--bg-tertiary)",
            color: canSubmit && !store.isLoading ? "#fff" : "var(--text-muted)",
            fontSize: "0.9375rem", fontWeight: 600, cursor: canSubmit && !store.isLoading ? "pointer" : "not-allowed", transition: "all 0.2s ease",
            boxShadow: canSubmit && !store.isLoading ? "0 2px 8px rgba(59,91,219,0.25)" : "none",
          }}>
            {store.isLoading ? <><Loader2 size={16} className="animate-spin" style={{ animation: "spin 1s linear infinite" }} /> {store.loadingMessage}</> : <><Sparkles size={16} /> Summarize</>}
          </button>

          {store.error && (
            <div style={{ display: "flex", alignItems: "center", gap: "8px", padding: "12px 16px", borderRadius: "var(--radius-md)", backgroundColor: "rgba(220,38,38,0.08)", color: "var(--accent-error)", fontSize: "0.875rem" }}>
              <AlertCircle size={16} /> {store.error}
            </div>
          )}
        </motion.div>

        {/* ── RIGHT: OUTPUT PANEL ── */}
        <motion.div initial={{ opacity: 0, x: 16 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.2 }}style={{
  borderRadius: "20px",
  border: "1px solid #dce5e9",
  backgroundColor: "#ffffff",
  minHeight: "540px",
  display: "flex",
  flexDirection: "column",
  boxShadow: "0 8px 30px rgba(11,52,69,0.06)",
}}>
          {store.isLoading ? (
            <div style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: "16px", padding: "48px" }}>
              <motion.div animate={{ rotate: 360 }} transition={{ duration: 2, repeat: Infinity, ease: "linear" }}>
                <Sparkles size={32} style={{ color: "var(--accent-primary)" }} />
              </motion.div>
              <p style={{ fontSize: "0.9375rem", fontWeight: 500, color: "var(--text-secondary)" }}>{store.loadingMessage}</p>
              <div style={{ width: "200px", height: "4px", borderRadius: "var(--radius-full)", backgroundColor: "var(--bg-tertiary)", overflow: "hidden" }}>
                <motion.div animate={{ x: ["-100%", "100%"] }} transition={{ duration: 1.5, repeat: Infinity }} style={{ width: "40%", height: "100%", borderRadius: "var(--radius-full)", backgroundColor: "var(--accent-primary)" }} />
              </div>
            </div>
          ) : store.result ? (
            <div style={{ padding: "24px", display: "flex", flexDirection: "column", gap: "20px" }}>
              {/* Headline */}
              {store.result.headline && (
                <motion.h2 initial={{ opacity: 0 }} animate={{ opacity: 1 }} style={{ fontFamily: "var(--font-sans )", fontSize: "1.5rem", lineHeight: 1.2, color: "var(--text-primary)" }}>
                  {store.result.headline}
                </motion.h2>
              )}

              {/* Summary Text */}
              <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} style={{ fontSize: "0.9375rem", lineHeight: 1.75, color: "var(--text-secondary)", whiteSpace: "pre-wrap" }}>
                {store.result.bullet_summary ? (
                  <ul style={{ listStyleType: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "12px" }}>
                    {store.result.bullet_summary.split("\n").map((line, i) => (
                      <li key={i} style={{ display: "flex", alignItems: "flex-start" }}>{line}</li>
                    ))}
                  </ul>
                ) : (
                  store.result.summary
                )}
              </motion.div>

              {/* Key Points */}
              {store.result.key_points.length > 0 && (
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.2 }} style={{ borderTop: "1px solid var(--border-subtle)", paddingTop: "16px" }}>
                  <p style={{ fontSize: "0.6875rem", fontWeight: 600, letterSpacing: "0.08em", textTransform: "uppercase", color: "var(--text-muted)", marginBottom: "10px" }}>Key Points</p>
                  <ul style={{ listStyle: "none", padding: 0, display: "flex", flexDirection: "column", gap: "8px" }}>
                    {store.result.key_points.slice(0, 5).map((point, i) => (
                      <motion.li key={i} initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.3 + i * 0.05 }} style={{ display: "flex", gap: "8px", fontSize: "0.875rem", color: "var(--text-tertiary)", lineHeight: 1.5 }}>
                        <CheckCircle2 size={14} style={{ color: "var(--accent-primary)", flexShrink: 0, marginTop: "3px" }} />
                        {truncateText(point, 150)}
                      </motion.li>
                    ))}
                  </ul>
                </motion.div>
              )}

              {/* Verification Panel */}
              {store.result.verification && (
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.3 }} style={{ border: "1px solid var(--border-subtle)", borderRadius: "var(--radius-md)", backgroundColor: "var(--bg-secondary)", padding: "16px" }}>
                  <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "12px", marginBottom: "12px" }}>
                    <div>
                      <p style={{ fontSize: "0.6875rem", fontWeight: 600, letterSpacing: "0.08em", textTransform: "uppercase", color: "var(--text-muted)", margin: 0 }}>Summary Reliability</p>
                      <div style={{ display: "flex", alignItems: "center", gap: "8px", marginTop: "8px" }}>
                        <span style={{ fontSize: "1.5rem", fontWeight: 700, color: "var(--text-primary)" }}>{Math.round(store.result.verification.reliability_score * 100)}%</span>
                        <span style={{ display: "inline-flex", alignItems: "center", gap: "4px", padding: "4px 8px", borderRadius: "var(--radius-full)", fontSize: "0.75rem", color: "var(--accent-success)", backgroundColor: "rgba(34, 197, 94, 0.12)" }}>
                          <CheckCircle2 size={12} /> {store.result.verification.supported_claims} supported
                        </span>
                        {store.result.verification.unsupported_claims > 0 && (
                          <span style={{ display: "inline-flex", alignItems: "center", gap: "4px", padding: "4px 8px", borderRadius: "var(--radius-full)", fontSize: "0.75rem", color: "var(--accent-warning)", backgroundColor: "rgba(245, 158, 11, 0.12)" }}>
                            <AlertCircle size={12} /> {store.result.verification.unsupported_claims} needs review
                          </span>
                        )}
                      </div>
                    </div>
                    <div style={{ width: "120px", height: "8px", borderRadius: "999px", backgroundColor: "var(--bg-tertiary)", overflow: "hidden" }}>
                      <div style={{ width: `${Math.round(store.result.verification.reliability_score * 100)}%`, height: "100%", borderRadius: "999px", backgroundColor: store.result.verification.unsupported_claims > 0 ? "var(--accent-warning)" : "var(--accent-success)" }} />
                    </div>
                  </div>

                  {store.result.verification.claims.length > 0 && (
                    <div style={{ display: "flex", flexDirection: "column", gap: "8px", marginTop: "8px" }}>
                      {store.result.verification.claims.map((claim, index) => (
                        <div key={`${claim.text}-${index}`} style={{ padding: "10px 12px", borderRadius: "var(--radius-sm)", border: "1px solid var(--border-subtle)", backgroundColor: "var(--bg-card)" }}>
                          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "8px", marginBottom: "4px" }}>
                            <span style={{ fontSize: "0.75rem", fontWeight: 600, color: claim.status === "supported" ? "var(--accent-success)" : "var(--accent-warning)" }}>
                              {claim.status === "supported" ? "✓ Supported" : "⚠ Needs review"}
                            </span>
                            <span style={{ fontSize: "0.6875rem", color: "var(--text-muted)" }}>{claim.support_score > 0 ? "Matched" : "Not found"}</span>
                          </div>
                          <p style={{ fontSize: "0.8125rem", color: "var(--text-secondary)", margin: 0, lineHeight: 1.5 }}>{claim.text}</p>
                          <p style={{ fontSize: "0.75rem", color: "var(--text-muted)", margin: "6px 0 0", lineHeight: 1.4 }}>{claim.evidence}</p>
                          {store.result.verification.external_fact_check_enabled && (
                            <div style={{ marginTop: "8px", paddingTop: "8px", borderTop: "1px solid var(--border-subtle)" }}>
                              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "8px", marginBottom: "4px" }}>
                                <span style={{ fontSize: "0.6875rem", fontWeight: 600, color: "var(--text-muted)", letterSpacing: "0.06em", textTransform: "uppercase" }}>
                                  External Fact Check
                                </span>
                                <span style={{ fontSize: "0.6875rem", color: claim.external_verified ? "var(--accent-success)" : "var(--accent-warning)" }}>
                                  {claim.external_verified ? `Verified via ${claim.external_provider || "external source"}` : claim.external_provider ? `Not confirmed via ${claim.external_provider}` : "External check unavailable"}
                                </span>
                              </div>
                              {claim.external_match_score !== null && claim.external_match_score !== undefined && (
                                <p style={{ fontSize: "0.75rem", color: "var(--text-muted)", margin: "0 0 4px", lineHeight: 1.4 }}>
                                  Match score: {claim.external_match_score.toFixed(2)}
                                </p>
                              )}
                              {claim.external_evidence && (
                                <p style={{ fontSize: "0.75rem", color: "var(--text-muted)", margin: 0, lineHeight: 1.4 }}>{claim.external_evidence}</p>
                              )}
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  )}
                </motion.div>
              )}

              {/* Analytics Badges */}
              <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.4 }} style={{ display: "flex", flexWrap: "wrap", gap: "8px", borderTop: "1px solid var(--border-subtle)", paddingTop: "16px" }}>
                <span style={{ display: "inline-flex", alignItems: "center", gap: "4px", padding: "4px 10px", borderRadius: "var(--radius-full)", fontSize: "0.75rem", fontWeight: 500, backgroundColor: "var(--accent-primary-light)", color: "var(--accent-primary)" }}>
                  <TrendingUp size={12} /> {store.result.analytics.sentiment}
                </span>
                <span style={{ display: "inline-flex", alignItems: "center", gap: "4px", padding: "4px 10px", borderRadius: "var(--radius-full)", fontSize: "0.75rem", fontWeight: 500, backgroundColor: "var(--accent-primary-light)", color: "var(--accent-primary)" }}>
                  <Clock size={12} /> {formatSeconds(store.result.analytics.reading_time_saved)} saved
                </span>
                <span style={{ display: "inline-flex", alignItems: "center", gap: "4px", padding: "4px 10px", borderRadius: "var(--radius-full)", fontSize: "0.75rem", fontWeight: 500, backgroundColor: "var(--accent-primary-light)", color: "var(--accent-primary)" }}>
                  <BarChart3 size={12} /> {Math.round(store.result.analytics.confidence_score * 100)}% confidence
                </span>
                <span style={{ display: "inline-flex", alignItems: "center", gap: "4px", padding: "4px 10px", borderRadius: "var(--radius-full)", fontSize: "0.75rem", fontWeight: 500, backgroundColor: "var(--accent-primary-light)", color: "var(--accent-primary)" }}>
                  <Hash size={12} /> {store.result.analytics.original_word_count} → {store.result.analytics.summary_word_count} words
                </span>
              </motion.div>

              {/* Keywords */}
              {store.result.analytics.keywords.length > 0 && (
                <div style={{ display: "flex", flexWrap: "wrap", gap: "6px" }}>
                  {store.result.analytics.keywords.map((kw) => (
                    <span key={kw} style={{ padding: "3px 10px", borderRadius: "var(--radius-full)", fontSize: "0.75rem", border: "1px solid var(--border-default)", color: "var(--text-tertiary)" }}>{kw}</span>
                  ))}
                </div>
              )}

              {/* Action Buttons */}
              <div style={{ display: "flex", gap: "8px", borderTop: "1px solid var(--border-subtle)", paddingTop: "16px" }}>
                <button onClick={handleCopy} style={{ display: "flex", alignItems: "center", gap: "6px", padding: "8px 14px", borderRadius: "var(--radius-md)", border: "1px solid var(--border-default)", backgroundColor: "var(--bg-card)", fontSize: "0.8125rem", fontWeight: 500, cursor: "pointer", color: copied ? "var(--accent-success)" : "var(--text-tertiary)", transition: "all 0.2s ease" }}>
                  {copied ? <CheckCircle2 size={14} /> : <Copy size={14} />} {copied ? "Copied" : "Copy"}
                </button>
                <button onClick={handleDownload} style={{ display: "flex", alignItems: "center", gap: "6px", padding: "8px 14px", borderRadius: "var(--radius-md)", border: "1px solid var(--border-default)", backgroundColor: "var(--bg-card)", fontSize: "0.8125rem", fontWeight: 500, cursor: "pointer", color: "var(--text-tertiary)", transition: "all 0.2s ease" }}>
                  <Download size={14} /> Download
                </button>
                <button onClick={handleSummarize} style={{ display: "flex", alignItems: "center", gap: "6px", padding: "8px 14px", borderRadius: "var(--radius-md)", border: "1px solid var(--border-default)", backgroundColor: "var(--bg-card)", fontSize: "0.8125rem", fontWeight: 500, cursor: "pointer", color: "var(--text-tertiary)", transition: "all 0.2s ease" }}>
                  <RefreshCw size={14} /> Regenerate
                </button>
              </div>
            </div>
          ) : (
            /* Empty State */
            <div style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "48px 32px", textAlign: "center" }}>
              <div style={{ width: "64px", height: "64px", borderRadius: "var(--radius-lg)", backgroundColor: "var(--bg-secondary)", display: "flex", alignItems: "center", justifyContent: "center", marginBottom: "20px" }}>
                <FileText size={28} style={{ color: "var(--text-muted)" }} />
              </div>
              <h3
  style={{
    fontFamily: "var(--font-sans)",
    fontSize: "1.25rem",
    fontWeight: 500,
    marginBottom: "8px",
    ccolor: "var(--text-primary)",
  }}
>Your summary will appear here</h3>
              <p style={{ fontSize: "0.875rem", color: "var(--text-muted)", maxWidth: "300px", lineHeight: 1.6 }}>Paste an article, enter a URL, or upload a document to get started.</p>
            </div>
          )}
        </motion.div>
      </div>

      <style jsx global>{`
        @media (max-width: 768px) {
          .summarize-grid { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </div>
  );
}
